package modelo.accesodatos;
// Generated 07-may-2013 20:22:16 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name="solicitud"
    ,catalog="sdt"
)
public class Solicitud  implements java.io.Serializable {


     private int idSolicitud;
     private Taxi taxi;
     private String nombreCliente;
     private String fechaSolicitud;
     private String direccionDestino;
     private String telefono;

    public Solicitud() {
    }

	
    public Solicitud(int idSolicitud, Taxi taxi) {
        this.idSolicitud = idSolicitud;
        this.taxi = taxi;
    }
    public Solicitud(int idSolicitud, Taxi taxi, String nombreCliente, String fechaSolicitud, String direccionDestino, String telefono) {
       this.idSolicitud = idSolicitud;
       this.taxi = taxi;
       this.nombreCliente = nombreCliente;
       this.fechaSolicitud = fechaSolicitud;
       this.direccionDestino = direccionDestino;
       this.telefono = telefono;
    }
   
     @Id 
    
    @Column(name="idSolicitud", unique=true, nullable=false)
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Taxi_NumBastidor", nullable=false)
    public Taxi getTaxi() {
        return this.taxi;
    }
    
    public void setTaxi(Taxi taxi) {
        this.taxi = taxi;
    }
    
    @Column(name="nombreCliente", length=45)
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    
    @Column(name="fechaSolicitud", length=45)
    public String getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(String fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    
    @Column(name="direccionDestino", length=45)
    public String getDireccionDestino() {
        return this.direccionDestino;
    }
    
    public void setDireccionDestino(String direccionDestino) {
        this.direccionDestino = direccionDestino;
    }
    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


