package modelo.accesodatos;
// Generated 07-may-2013 20:22:16 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Taxi generated by hbm2java
 */
@Entity
@Table(name="taxi"
    ,catalog="sdt"
)
public class Taxi  implements java.io.Serializable {


     private int numBastidor;
     private String estado;
     private String ubicacion;
     private String destino;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<Solicitud> solicituds_1 = new HashSet<Solicitud>(0);

    public Taxi() {
    }

	
    public Taxi(int numBastidor) {
        this.numBastidor = numBastidor;
    }
    public Taxi(int numBastidor, String estado, String ubicacion, String destino, Set<Solicitud> solicituds, Set<Solicitud> solicituds_1) {
       this.numBastidor = numBastidor;
       this.estado = estado;
       this.ubicacion = ubicacion;
       this.destino = destino;
       this.solicituds = solicituds;
       this.solicituds_1 = solicituds_1;
    }
   
     @Id 
    
    @Column(name="NumBastidor", unique=true, nullable=false)
    public int getNumBastidor() {
        return this.numBastidor;
    }
    
    public void setNumBastidor(int numBastidor) {
        this.numBastidor = numBastidor;
    }
    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="ubicacion", length=45)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    
    @Column(name="destino", length=45)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="taxi")
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="taxi")
    public Set<Solicitud> getSolicituds_1() {
        return this.solicituds_1;
    }
    
    public void setSolicituds_1(Set<Solicitud> solicituds_1) {
        this.solicituds_1 = solicituds_1;
    }




}


